title: "Tejas's R&R Travels"
name: "Tejas Sharma"
copyright: "Tejas Sharma"
repository: "tejassharma96/blog"
description: "Follow along as Tejas travels through around!"
baseurl: "/blog"
url: ""
minimal_mistakes_skin: dark

# remote_theme: vaibhavvikas/jekyll-theme-minimalistic
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-remote-cache

collections:
  posts:
    output: true

atom_feed:
  hide: true

search: true
lunr:
  search_within_pages: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: false

nav:
  - name: Home
    link: /
  - name: Timeline
    link: /timeline/

markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title/
